### ISSUE TITLE
Crash on loading shapes/Shape.lua

### ISSUE THREAD

**Issue by Nattie-G** [Aweptimum/Strike#2]
I ran into this crash on require of the library on a fresh install (after copying DeWallua into libs). It's caused by running a minimal LOVE project under and requiring Strike. It happens every time and seems to stem from some unexpected behaviour from classic.lua.
I'm running Manjaro Linux and using love 11.3

```path: Strike.lib.DeWallua.vector-light
path: Strike.shapes
path: Strike.scandir
path: Strike.shapes.Shape
Error: Strike/shapes/Shape.lua:7: attempt to index local 'Object' (a nil value)
stack traceback:
	[string "boot.lua"]:777: in function '__index'
	Strike/shapes/Shape.lua:7: in main chunk
	[C]: in function '_Require_relative'
	Strike/shapes.lua:2: in main chunk
	[C]: in function '_Require_relative'
	Strike/Strike.lua:2: in main chunk
	[C]: in function 'require'
	Strike/init.lua:26: in main chunk
	[C]: in function 'require'
	main.lua:1: in main chunk
	[C]: in function 'require'
	[string "boot.lua"]:570: in function <[string "boot.lua"]:380>
	[C]: in function 'xpcall'
	[string "boot.lua"]:787: in function <[string "boot.lua"]:780>
	[C]: in function 'xpcall'```

**Comment by Aweptimum** [comment]
It appears this is caused by the love-specific `scandir` function. Currently, the appended `"."` in its definition is preventing `love.filesystem.getDirectoryItems` from looking through the `lib` directory correctly. Removing it fixes this.

I found another crash caused by `require('shape')` present in the 2 base classes, `ConvexPolygon` and `Circle`. This fails for case-sensitive filesystems and should be `require('Shape')` (my bad). I'll PR the fix for both later today.

Thanks for your patience and help!

**Comment by Nattie-G** [comment]
I've tested this PR, and confirmed it resolves the issue!
